# Generated by Django 4.0.10 on 2025-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_section', models.CharField(max_length=20)),
                ('professor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
