# Generated by Django 5.1.7 on 2025-04-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_section', models.CharField(max_length=20)),
                ('professor_name', models.CharField(max_length=50)),
                ('prelims', models.CharField(max_length=10)),
                ('midterms', models.CharField(max_length=10)),
                ('semifinals', models.CharField(max_length=10)),
                ('finals', models.CharField(max_length=10)),
                ('gwa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
