# Generated by Django 5.0.14 on 2025-04-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('student_section', models.CharField(max_length=20)),
                ('professor_name', models.CharField(max_length=50)),
                ('prelims', models.CharField(max_length=10)),
                ('midterms', models.CharField(max_length=10)),
                ('semifinals', models.CharField(max_length=10)),
                ('finals', models.CharField(max_length=10)),
                ('gwa', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students_student',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
