# Generated by Django 5.0.14 on 2025-04-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_delete_student_delete_studentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
