# version: '3.9'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 #uncomment for production :3
    # command: python /code/manage.py runserver 0.0.0.0:8000 #uncomment for development
    volumes:
      - .:/code  # Mount the current directory as /code in the container
    ports:
      - "8000:8000"  # Expose port 8000 on both the host and the container
    environment:
      - "DJANGO_SECRET_KEY=your-secret-key"
      - "DJANGO_DEBUG=True"
